### ISSUE TITLE
Not work / linux vps

### ISSUE THREAD

**Issue by 52rpm** [orewaee/donation-notifications#1]
fixit

**Comment by orewaee** [comment]
You probably don't have the required dependencies installed. Use (depending on your package manager) one of the commands: `npm install` or `yarn install`.

You also use the `node src/main.ts` command to start the application. You must (depending on your package manager) use `npm run start` or `yarn start`.

Before starting, make sure to set up environment variables. Their list can be seen in the `.env.example` file.

**Comment by 52rpm** [comment]
i use both npm install and yarn install.

where i need create .env ? in src folder?

i create in src folder and what about **url hook** is discord webhook or i need setup nginx fot https ?

**Comment by orewaee** [comment]
The `.env` file must be created in the `donation-notifications` folder.

Nothing needs to be configured, Discord Webhook is used. You can get it in your Discord server settings.

**Comment by 52rpm** [comment]
i run script , i make test donation but nothing pushing to discord! What mean :  **ID - id of the Discord user who will be pinged with a new donation.**

![1d](https://user-images.githubusercontent.com/89786075/201472956-9f9817d4-4e4f-43fb-8c9a-0958a128e44c.png)

**Comment by orewaee** [comment]
When you make a test donation, you must check the box "Alert donation in widget", only then it will be displayed. This is not required for real donations.

But if you send a donation now, it still won't show up. Your application is trying to reconnect to the socket, but for some reason is unable to do so. You most likely entered the wrong DonationAlerts token. To get it, select "Account Settings" in the top right navigation after clicking on your profile. Next, at the bottom, find the "Secret token:" field and copy what is hidden.

The `ID` environment variable is the Discord ID of the user you want to ping on a new donation.

**Comment by 52rpm** [comment]
not working ! need script to push new donate to channel

**Comment by orewaee** [comment]
To send text messages to a specific channel, I used webhooks. You can find more information about them [here](https://discordjs.guide/popular-topics/webhooks.html#what-is-a-webhook).

**Comment by 52rpm** [comment]
iam not stupid i create webhook , i get user id from discord i get token from donationalerts i do all! This script not work! or have external lib
